# Generated by Django 4.1 on 2022-10-04 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='founder',
            name='desc',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
