# Generated by Django 4.1 on 2022-10-04 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_founder_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultant',
            name='desc',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manager',
            name='desc',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='travel',
            name='desc',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
